openapi: 3.0.3
info:
  title: API Jiki Skincare
  description: API para gerenciamento e venda de produtos de skincare
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /produtos:
    get:
      summary: Lista todos os produtos
      responses:
        '200':
          description: Lista de produtos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Produto'
    post:
      summary: Cria um novo produto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
      responses:
        '201':
          description: Produto criado
  /produtos/{id}:
    get:
      summary: Busca um produto pelo ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Produto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        '404':
          description: Produto não encontrado
    put:
      summary: Atualiza um produto existente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
      responses:
        '200':
          description: Produto atualizado
    delete:
      summary: Remove um produto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Produto removido
components:
  schemas:
    Produto:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome:
          type: string
          example: Esfoliante Facial
        preco:
          type: number
          format: float
          example: 29.90
        descricao:
          type: string
          example: Shampoo