spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgis_35_sample
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            '[non_contextual_creation]': true
    show-sql: true